-- 메뉴 테이블 생성
CREATE TABLE TB_MENU(
	MENU_ID VARCHAR2(10) CONSTRAINT MENU_ID_PK PRIMARY KEY,
	MENU_NAME VARCHAR2(20) CONSTRAINT MENU_NAME_NN NOT NULL,
	MENU_PRICE NUMBER
);

-- 메뉴 테이블 조회
SELECT * FROM TB_MENU;

-- 주문 테이블 생성
CREATE TABLE TB_ORDER(
	ORDER_NO NUMBER CONSTRAINT ORDER_NO_PK PRIMARY KEY,
	MENU_ID VARCHAR2(10) CONSTRAINT MENU_ID_FK REFERENCES TB_MENU(MENU_ID),
	ORDER_DATE DATE CONSTRAINT ORDER_DATE_NN NOT NULL
);

-- 주문 테이블 조회
SELECT * FROM TB_ORDER;

-- 메뉴 테이블 주석 생성
COMMENT ON COLUMN TB_MENU.MENU_ID IS '메뉴 아이디';
COMMENT ON COLUMN TB_MENU.MENU_NAME IS '메뉴명';
COMMENT ON COLUMN TB_MENU.MENU_PRICE IS '메뉴 가격';

-- 주문 테이블 주석 생성
COMMENT ON COLUMN TB_ORDER.ORDER_NO IS '주문 번호';
COMMENT ON COLUMN TB_ORDER.MENU_ID IS '메뉴 아이디';
COMMENT ON COLUMN TB_ORDER.ORDER_DATE IS '주문 일시';

-- 메뉴 테이블 값 추가
INSERT INTO TB_MENU VALUES('A01', '아메리카노', 3000);
INSERT INTO TB_MENU VALUES('A02', '카페라떼', 4000);
INSERT INTO TB_MENU VALUES('A03', '오렌지주스', 4500);

-- 메뉴 테이블 조회
SELECT * FROM TB_MENU;

-- 주문 테이블 시퀀스 생성
CREATE SEQUENCE SQ_ORDER_NO
START WITH 1
INCREMENT BY 1
NOCYCLE;

-- 주문 테이블 값 추가
INSERT INTO TB_ORDER VALUES(SQ_ORDER_NO.NEXTVAL, 'A01', SYSDATE);
INSERT INTO TB_ORDER VALUES(SQ_ORDER_NO.NEXTVAL, 'A02', SYSDATE);
INSERT INTO TB_ORDER VALUES(SQ_ORDER_NO.NEXTVAL, 'A03', SYSDATE);

-- 주문 테이블 조회
SELECT * FROM TB_ORDER;

-- 주문 테이블 수정
UPDATE TB_ORDER SET 
MENU_ID = 'A02'
WHERE ORDER_NO = 3;

-- 수정된 주문 테이블 조회
SELECT * FROM TB_ORDER;

-- 주문 테이블 값 삭제
DELETE FROM TB_ORDER WHERE ORDER_NO = 3;

-- 삭제된 주문 테이블 조회
SELECT * FROM TB_ORDER;

-- JOIN 구문을 통해 테이블 합치기
-- 1) 오라클 방식
SELECT
	*
FROM 
	TB_MENU M,
	TB_ORDER O
WHERE 1 = 1
  AND M.MENU_ID = O.MENU_ID;
 
-- 2) ANSI 방식
SELECT *
FROM TB_MENU 
JOIN TB_ORDER USING(MENU_ID);

-- 메뉴 테이블 삭제
DROP TABLE TB_MENU CASCADE CONSTRAINT;
SELECT * FROM TB_MENU;
SELECT * FROM TB_ORDER;

-- 주문 테이블 삭제
DROP TABLE TB_ORDER;
SELECT * FROM TB_ORDER;

-- 시퀀스 삭제
DROP SEQUENCE SQ_ORDER_NO;




