SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE,
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;
-- 항상 결과 잘 나오는지 확인하고 이클립스로 가져가기!

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMP_ID = 223;

