SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_GENDER,
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DT
FROM MEMBER
WHERE MEMBER_ID = 'user01'
AND MEMBER_PW = 'pass01'
AND UNREGISTER_FL = 'N';

INSERT INTO MEMBER(MEMBER_ID, MEMBER_PW, MEMBER_NM, MEMBER_GENDER)
VALUES(?, ?, ?, ?);

INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, ?, ?, DEFAULT, DEFAULT)

SELECT * FROM MEMBER;

SELECT MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NM, MEMBER_GENDER, TO_CHAR(ENROLL_DT, 'YYYYMMDD') ENROLL_DT, UNREGISTER_FL
FROM MEMBER
WHERE MEMBER_ID = ?;
