SELECT IMG_PATH, IMG_RENAME, IMG_ORIGINAL, IMG_ORDER
FROM BOARD_IMG
UNION ALL
SELECT IMG_PATH, IMG_RENAME, IMG_ORIGINAL, IMG_ORDER
FROM BOARD_IMG
UNION ALL
SELECT IMG_PATH, IMG_RENAME, IMG_ORIGINAL, IMG_ORDER
FROM BOARD_IMG;

SELECT * FROM BOARD;

