CREATE TABLE NOTICE_BOARD (
	NOTICE_NO NUMBER NOT NULL PRIMARY KEY,
	MANAGER_NO NUMBER NOT NULL,
	NOTICE_TITLE VARCHAR2(300) NOT NULL,
	NOTICE_DETAIL VARCHAR2(3000) NOT NULL,
	NOTICE_UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN NOTICE_BOARD.NOTICE_NO IS '공지사항 번호';
COMMENT ON COLUMN NOTICE_BOARD.MANAGER_NO IS '관리자 번호';
COMMENT ON COLUMN NOTICE_BOARD.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN NOTICE_BOARD.NOTICE_DETAIL IS '공지사항 내용';
COMMENT ON COLUMN NOTICE_BOARD.NOTICE_UPLOAD_DATE IS '공지사항 업로드 날짜';

CREATE SEQUENCE SEQ_NOTICE_NO;

INSERT INTO NOTICE_BOARD VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '공지사항제목1', '공지사항내용1', DEFAULT);
INSERT INTO NOTICE_BOARD VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '공지사항제목2', '공지사항내용2', DEFAULT);
INSERT INTO NOTICE_BOARD VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '공지사항제목3', '공지사항내용3', DEFAULT);
INSERT INTO NOTICE_BOARD VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '공지사항제목4', '공지사항내용4', DEFAULT);

COMMIT;

SELECT * FROM NOTICE_BOARD;

SELECT N.NOTICE_NO, N.MANAGER_NO, N.NOTICE_TITLE, N.NOTICE_DETAIL, TO_CHAR(N.NOTICE_UPLOAD_DATE, 'YYYY-MM-DD') NOTICE_UPLOAD_DATE
FROM NOTICE_BOARD N;
