-- 게시글 상세 조회
SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_CODE,
	READ_COUNT, MEMBER_NICKNAME, MEMBER_NO, PROFILE_IMG,
	TO_CHAR(B_CREATE_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') B_CREATE_DATE,
	TO_CHAR(B_UPDATE_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') B_UPDATE_DATE,
	(SELECT COUNT(*)
	FROM "BOARD_LIKE" L
	WHERE L.BOARD_NO = B.BOARD_NO) LIKE_COUNT
FROM "BOARD" B
JOIN "MEMBER" USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
AND BOARD_CODE = 1
AND BOARD_NO = 1998;


SELECT * FROM BOARD_LIKE;

-- 게시글 좋아요 샘플 데이터 삽입
INSERT INTO "BOARD_LIKE" VALUES(1998, 2);
INSERT INTO "BOARD_LIKE" VALUES(1998, 3);
COMMIT;


-- 특정 게시글에 대한 이미지 조회
SELECT * FROM BOARD_IMG
WHERE BOARD_NO = 1998
ORDER BY IMG_ORDER;

INSERT INTO BOARD_IMG
VALUES(SEQ_IMG_NO.NEXTVAL,
	'/resources/images/board/',
	'20230508115013_00001.jpg',
	'cat1.jpg',
	0,
	1998
);

INSERT INTO BOARD_IMG
VALUES(SEQ_IMG_NO.NEXTVAL,
	'/resources/images/board/',
	'20230508115013_00002.jpg',
	'cat2.jpg',
	1,
	1998
);

INSERT INTO BOARD_IMG
VALUES(SEQ_IMG_NO.NEXTVAL,
	'/resources/images/board/',
	'20230508115013_00003.jpg',
	'cat3.jpg',
	2,
	1998
);

COMMIT;




-- 특정 게시글에 대한 댓글 목록 조회
SELECT COMMENT_NO, COMMENT_CONTENT,
TO_CHAR(C_CREATE_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') C_CREATE_DATE,
BOARD_NO, MEMBER_NO, MEMBER_NICKNAME, PROFILE_IMG, PARENT_NO, COMMENT_DEL_FL
FROM "COMMENT"
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_NO = 1998
ORDER BY COMMENT_NO;


