UPDATE "MEMBER" SET
MEMBER_PW = '$2a$10$qk7n5YaG.LanzGrwA27ARuF13zgpZ7tHaFos0enHcS9fn4/Xes1wS'
WHERE MEMBER_NO = 1;

COMMIT;

SELECT * FROM "MEMBER";



SELECT MEMBER_TEL FROM "MEMBER"
WHERE MEMBER_NICKNAME = '유저일'
AND MEMBER_DEL_FL = 'N';