SELECT COUNT(*) FROM BOARD_LIKE
WHERE BOARD_NO = 2000
AND MEMBER_NO = 2;

SELECT * FROM BOARD_LIKE;

SELECT * FROM BOARD
WHERE BOARD_NO = 1998;

SELECT * FROM BOARD_LIKE;

INSERT INTO BOARD_LIKE VALUES();