-- 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER kh_test2 IDENTIFIED BY test1234;

GRANT RESOURCE, CONNECT TO kh_test2;

ALTER USER kh_test2 DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-------------------------------------------------------------------------------

-- TB_TODO 테이블 생성 및 SEQ_TODONO 시퀀스 생성
CREATE TABLE TB_TODO(
TODO_NO NUMBER PRIMARY KEY,
TODO_TITLE VARCHAR2(100) NOT NULL,
TODO_CONTENT VARCHAR2(300) NOT NULL
);

CREATE SEQUENCE SEQ_TODONO;

-- 샘플 데이터 삽입
INSERT INTO TB_TODO VALUES(SEQ_TODONO.NEXTVAL, '청소하기', '내 방 청소해야해');
INSERT INTO TB_TODO VALUES(SEQ_TODONO.NEXTVAL, '코딩하기', '스프링은 어려워~');
INSERT INTO TB_TODO VALUES(SEQ_TODONO.NEXTVAL, '운동하기', '오늘은 하체 하는 날');

COMMIT;

-- TB_TODO 테이블 조회
SELECT * FROM TB_TODO;

-- TB_TODO 테이블 조회
SELECT TODO_NO, TODO_TITLE, TODO_CONTENT
FROM TB_TODO;

