DROP TABLE MEMBER;

-- 멤버 테이블 생성
CREATE TABLE MEMBER (
	MEMBER_NO NUMBER NOT NULL PRIMARY KEY,
	MEMBER_ID VARCHAR2(50) NOT NULL,
	MEMBER_PW VARCHAR2(100) NOT NULL,
	MEMBER_NICKNAME VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
	MEMBER_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL
);

-- 멤버 테이블 주석
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호(SEQ_MEMBER_NO)';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NICKNAME IS '회원 이름(별명)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.MEMBER_DEL_FL IS '탈퇴여부(N:탈퇴X, Y:탈퇴O)';

DROP TABLE TODO;

-- 투두 테이블 생성
CREATE TABLE TODO (
	TODO_NO NUMBER NOT NULL PRIMARY KEY,
	TODO_TITLE VARCHAR2(300) NOT NULL,
	TODO_MEMO VARCHAR2(500),
	TODO_DATE DATE DEFAULT SYSDATE NOT NULL,
	TODO_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	CONSTRAINTS MEMBER_NO_FK FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

-- 투두 테이블 주석
COMMENT ON COLUMN TODO.TODO_NO IS '투두 번호(SEQ_TODO_NO)';
COMMENT ON COLUMN TODO.TODO_TITLE IS '투두 제목';
COMMENT ON COLUMN TODO.TODO_MEMO IS '투두 메모내용';
COMMENT ON COLUMN TODO.TODO_DATE IS '투두 생성일';
COMMENT ON COLUMN TODO.TODO_DEL_FL IS '삭제 여부(N: 삭제X, Y:삭제O)';
COMMENT ON COLUMN TODO.MEMBER_NO IS '작성자 회원 번호';

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO; 
CREATE SEQUENCE SEQ_TODO_NO;