-- 테이블 데이터 삽입
INSERT INTO TODO VALUES(SEQ_TODO_NO.NEXTVAL, '장보기', '이마트 장봐야함', DEFAULT, DEFAULT, 1);
INSERT INTO TODO VALUES(SEQ_TODO_NO.NEXTVAL, '칼퇴하기', '퇴근마렵다', DEFAULT, DEFAULT, 1);

-- COMMIT
COMMIT;

-- 테이블 데이터 삽입 확인
SELECT * FROM TODO;

SELECT TODO_NO, TODO_TITLE, TODO_MEMO, TO_CHAR(TODO_DATE, 'YYYY-MM-DD') TODO_DATE, TODO_DEL_FL
FROM TODO
WHERE MEMBER_NO = ?