-- 테이블 데이터 삽입
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT, DEFAULT);

-- COMMIT
COMMIT;

-- 테이블 데이터 삽입 확인
SELECT * FROM MEMBER;

SELECT MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, TO_CHAR(ENROLL_DATE, 'YYYY-MM-DD') ENROLL_DATE, MEMBER_DEL_FL
FROM MEMBER
WHERE MEMBER_ID = ?
AND MEMBER_PW = ?